--Select
SELECT * FROM (
	SELECT DISTINCT cl.IDCLIENTE, cl.NOME, cl.UF, cl.CELULAR 
	FROM CLIENTES cl
	INNER JOIN FINANCIAMENTOS fin ON cl.IDCLIENTE = fin.IDCLIENTE
	INNER JOIN PARCELAS parc ON parc.IDFINANCIAMENTO = fin.IDFINANCIAMENTO
	WHERE (PARC.PAGAMENTO > PARC.VENCIMENTO + 5 OR (parc.VENCIMENTO < SYSDATE and parc.PAGAMENTO IS null))
	ORDER BY cl.IDCLIENTE
) WHERE ROWNUM <= 4;


SELECT DISTINCT cl.IDCLIENTE, cl.NOME, cl.UF, cl.CELULAR 
FROM CLIENTES cl
INNER JOIN FINANCIAMENTOS fin ON cl.IDCLIENTE = fin.IDCLIENTE
INNER JOIN PARCELAS parc ON parc.IDFINANCIAMENTO = fin.IDFINANCIAMENTO
WHERE (PARC.PAGAMENTO > PARC.VENCIMENTO + 10 OR (parc.VENCIMENTO > SYSDATE and parc.VENCIMENTO IS null))
AND fin.VALORTOTAL > 10000 ORDER BY cl.IDCLIENTE;